server:
  max-http-header-size: 4048576
  port: 8069
cer:
  pkcs12path: apiclient_cert.p12

bootdo:
  uploadPath: D:\\k2_coach\\k3\\files\\
  httpUrl: http://192.168.0.168/files/
  username: admin
  password: 111111
logging:
  level:
    root: info
    com.bootdo: debug
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zn_coach?useUnicode=true&characterEncoding=utf8
    username: root
    password: aa**1330
    #    password: 123456
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
  redis:
    host: 127.0.0.1
    port: 6379
    #  password:
    password: aa**1330
    # 连接超时时间（毫秒）
    timeout: 10000
    jedis:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 10
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1

#微信 公众号支付相关配置
weixin:
  #app_secret
  app_secret: 423dd16000ed46b3e28b98aed0b4c11b
  #收费微信账号(由系统设置)
  charge_account: 领航e驾路考仪厂家
  #APP账号ID appid
  app_id: wx192e0ea49320ff78
  #商户号    mch_id
  mch_id: 1521218591
  #支付秘钥
  api_key: shenzhenshihaizhenxingkeji201812
  #商品描述 body
  body: 考试费用
  #请求超时时间
  timeout: 3000
  #关注回调地址 callbackUrl
  callbackUrl:
  #异步回调地址 notify_url
  notify_url: http://jpjlxy.top/coach_background/student/weixinPayResult


#  测试号管理微信号： gh_1f05757a4e50  退出
#  测试号信息
#  appID
#  wxb5795280fcc4f9c8
#  appsecret
#  22275bd3264c3198720ca55654457828

mina:
  port: 1331

#预付费用
prepaid_expenses: 1