server:
  max-http-header-size: 4048576
  port: 8069
cer:
  pkcs12path: apiclient_cert.p12
bootdo:
  #河北
  uploadPath: /home/hzx/k2/files/
  httpUrl: http://coach.kaimatekeji.com/files/
  username: admin
  password: 111111
logging:
  config: classpath:log4j2.xml
  level:
    root: info
    com.bootdo: debug
spring:
  datasource:
    #河北
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://coach.kaimatekeji.com:3168/zn_coach
    username: root
    password: Hb@20191225
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
  redis:
    #河北
    database: 2
    host: localhost
    port: 6379
    password: Hb@20191225
    # 连接超时时间（毫秒）
    timeout: 10000
    jedis:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 10
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1

#微信 公众号支付相关配置
weixin:
  #河北
  #app_secret
  app_secret: 93555f27b1b49eac1ac6c6a40888f35f
  #收费微信账号(由系统设置)
  charge_account: 领航e驾路考仪厂家
  #APP账号ID appid
  app_id: wx2a5d81f67d68a076
  #商户号    mch_id
  mch_id: 1446626402
  #支付秘钥
  api_key: nmxt0020191228nmxt00201912281668
  #商品描述 body
  body: 考试费用
  #请求超时时间
  timeout: 3000
  #关注回调地址 callbackUrl
  callbackUrl:
  #异步回调地址 notify_url
  notify_url: http://coach.kaimatekeji.com/coach_background/student/weixinPayResult


#  测试号管理微信号： gh_1f05757a4e50  退出
#  测试号信息
#  appID
#  wxb5795280fcc4f9c8
#  appsecret
#  22275bd3264c3198720ca55654457828
mina:
  port: 1331

#预付费用
prepaid_expenses: 1